name: Contributor License Agreement Policy
description: CLA policy file
resource: repository

configuration:
  cla:
    content: https://raw.githubusercontent.com/microsoft/ContributorLicenseAgreement/main/CLA.md

    minimalChangeRequired:
      files: 1

    bypassUsers:
      - python-lsp-compare-bot
      - python-lsp-compare-bot[bot]
      - github-actions[bot]
